// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62RqjIALXrIoeY1UR9de5Wt-kxejLxVg',
    appId: '1:818972323672:web:c9e40b9b737847e8ddff2d',
    messagingSenderId: '818972323672',
    projectId: 'learn-flutter-68-2-84af2',
    authDomain: 'learn-flutter-68-2-84af2.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-84af2.firebasestorage.app',
    measurementId: 'G-K88HMX3KGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwxZvLHiapDz_-kbcPilLqFcYAlrNVyI',
    appId: '1:818972323672:android:a571b8fa8ec2d742ddff2d',
    messagingSenderId: '818972323672',
    projectId: 'learn-flutter-68-2-84af2',
    storageBucket: 'learn-flutter-68-2-84af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwLFjq41RjPwvyY9rYsYzrhA1ESzv4lg',
    appId: '1:818972323672:ios:a83a7d4ce023bea6ddff2d',
    messagingSenderId: '818972323672',
    projectId: 'learn-flutter-68-2-84af2',
    storageBucket: 'learn-flutter-68-2-84af2.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZwLFjq41RjPwvyY9rYsYzrhA1ESzv4lg',
    appId: '1:818972323672:ios:a83a7d4ce023bea6ddff2d',
    messagingSenderId: '818972323672',
    projectId: 'learn-flutter-68-2-84af2',
    storageBucket: 'learn-flutter-68-2-84af2.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA62RqjIALXrIoeY1UR9de5Wt-kxejLxVg',
    appId: '1:818972323672:web:760cc046ab835195ddff2d',
    messagingSenderId: '818972323672',
    projectId: 'learn-flutter-68-2-84af2',
    authDomain: 'learn-flutter-68-2-84af2.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2-84af2.firebasestorage.app',
    measurementId: 'G-JWM4BQXVMB',
  );
}
